INSERT INTO expense_category(name) VALUES ('Car'),
                                          ('Moto'),
                                          ('Improvement'),
                                          ('Clothes'),
                                          ('Travel'),
                                          ('Insurance'),
                                          ('Gifts'),
                                          ('Apartment'),
                                          ('Parents'),
                                          ('Health'),
                                          ('Sport'),
                                          ('Entertainment'),
                                          ('Girlfriend'),
                                          ('Benefaction'),
                                          ('Business'),
                                          ('Other')